[project]
name = "gameboost-tl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "python-dotenv>=1.0.1",
    "seleniumbase>=4.33.11",
    "beautifulsoup4>=4.12.3",
    "pydantic>=2.10.4",
    "gspread>=6.1.4",
]
